export const JOBS_COMPLETE_REQUEST = 'JOBS_COMPLETE_REQUEST';
export const JOBS_COMPLETE_SUCCESS = 'JOBS_COMPLETE_SUCCESS';
export const JOBS_COMPLETE_FAIL = 'JOBS_COMPLETE_FAIL';

export const NEXT_JOBS_COMPLETE_REQUEST = 'NEXT_JOBS_COMPLETE_REQUEST';
export const NEXT_JOBS_COMPLETE_SUCCESS = 'NEXT_JOBS_COMPLETE_SUCCESS';
export const NEXT_JOBS_COMPLETE_FAIL = 'NEXT_JOBS_COMPLETE_FAIL';

export const REFRESH_JOBS_COMPLETE_REQUEST = 'REFRESH_JOBS_COMPLETE_REQUEST';
export const REFRESH_JOBS_COMPLETE_SUCCESS = 'REFRESH_JOBS_COMPLETE_SUCCESS';
export const REFRESH_JOBS_COMPLETE_FAIL = 'REFRESH_JOBS_COMPLETE_FAIL';

export const UPDATE_PAGE = 'UPDATE_PAGE';
