export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const EDIT_CIMAGE_REQUEST = 'EDIT_CIMAGE_REQUEST';
export const EDIT_CIMAGE_SUCCESS = 'EDIT_CIMAGE_SUCCESS';
export const EDIT_CIMAGE_FAIL = 'EDIT_CIMAGE_FAIL';
