import {StyleSheet} from 'react-native';
import {screenWidth, screenHeight} from '../../utils/helpers';
const styles = StyleSheet.create({
  bg: {
    backgroundColor: '#31aab7',
    height: screenWidth / 2.6,
  },
  fx: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  imgCont: {
    borderWidth: 2,
    borderColor: '#FFFF',
    height: screenWidth / 2.5,
    width: screenWidth / 2.5,
    borderRadius: screenWidth / 2.5 / 2,
    alignSelf: 'center',
    marginTop: -screenWidth / 2.5 / 2,
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 10,
    elevation: 3,
  },
  img: {
    height: screenWidth / 2.6,
    width: screenWidth / 2.6,
    borderRadius: screenWidth / 2.6 / 2,
    alignSelf: 'center',
  },
  name: {
    color: '#343434',
    fontWeight: 'bold',
    fontFamily: 'Poppins-Regular',
    fontSize: 20,
    marginBottom: 6,
    alignSelf: 'center',
    marginHorizontal: 20,
    marginVertical: 2,
  },
  email: {
    color: '#343434',
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    marginBottom: 6,
    alignSelf: 'center',
    marginHorizontal: 20,
    marginVertical: 2,
  },
  btn: {
    width: screenWidth / 4,
    backgroundColor: '#31AAB7',
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
    alignSelf: 'center',
    marginTop: 20,
  },
  btntxt: {
    color: '#FFFF',
    fontFamily: 'Poppins-Regular',
    fontSize: 10,
  },
  backButtonContainer: {
    backgroundColor: '#F4F4F4',
    borderRadius: 50,
    width: 80,
    marginBottom: 20,
    marginTop: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  backButtonText: {
    color: '#787777',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    textAlignVertical: 'center',
  },
  titleText: {
    color: '#787777',
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    textAlignVertical: 'center',
  },
  bottomText: {
    color: '#787777',
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    width: screenWidth / 1.5,
  },
  cont: {
    backgroundColor: '#F9F9F9',
    width: screenWidth / 1.1,
    alignSelf: 'center',
    marginVertical: 20,
    borderRadius: 5,
  },
  main: {
    width: screenWidth / 1.1,
    alignSelf: 'center',
  },
  key: {
    marginTop: 20,
    flex: 1,
  },
  camview: {
    backgroundColor: '#E7E7E7',
    borderRadius: 20,
    width: 40,
    height: 40,
    position: 'absolute',
    bottom: 0,
    right: 0,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },

  btnoption: {
    height: 45,
    width: screenWidth,
    borderBottomColor: 'black',
    borderBottomWidth: 1,
    justifyContent: 'center',
  },
  optionsub: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  optionImg: {
    height: 25,
    width: 25,
    resizeMode: 'contain',
    marginLeft: 10,
    tintColor: '#31AAB7',
  },
  optionImgNew: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
    marginLeft: 10,
    tintColor: '#31AAB7',
  },
  optionTxt: {
    fontSize: 18,
    fontFamily: 'Poppins-Regular',
    marginLeft: 10,
  },
});

export default styles;
