export const JOBS_INVITE_REQUEST = 'JOBS_INVITE_REQUEST';
export const JOBS_INVITE_SUCCESS = 'JOBS_INVITE_SUCCESS';
export const JOBS_INVITE_FAIL = 'JOBS_INVITE_FAIL';

export const NEXT_JOBS_INVITE_REQUEST = 'NEXT_JOBS_INVITE_REQUEST';
export const NEXT_JOBS_INVITE_SUCCESS = 'NEXT_JOBS_INVITE_SUCCESS';
export const NEXT_JOBS_INVITE_FAIL = 'NEXT_JOBS_INVITE_FAIL';

export const REFRESH_JOBS_INVITE_REQUEST = 'REFRESH_JOBS_INVITE_REQUEST';
export const REFRESH_JOBS_INVITE_SUCCESS = 'REFRESH_JOBS_INVITE_SUCCESS';
export const REFRESH_JOBS_INVITE_FAIL = 'REFRESH_JOBS_INVITE_FAIL';

export const UPDATE_PAGE = 'UPDATE_PAGE';

export const JOB_REJECT_INVITE_REQUEST = 'JOB_REJECT_INVITE_REQUEST';
export const JOB_REJECT_INVITE_SUCCESS = 'JOB_REJECT_INVITE_SUCCESS';
export const JOB_REJECT_INVITE_FAIL = 'JOB_REJECT_INVITE_FAIL';

export const JOB_ACCEPT_INVITE_REQUEST = 'JOB_ACCEPT_INVITE_REQUEST';
export const JOB_ACCEPT_INVITE_SUCCESS = 'JOB_ACCEPT_INVITE_SUCCESS';
export const JOB_ACCEPT_INVITE_FAIL = 'JOB_ACCEPT_INVITE_FAIL';
