import {StyleSheet, Dimensions} from 'react-native';
import {screenWidth, screenHeight} from '../../utils/helpers';
const {width, height} = Dimensions.get('window');
const styles = StyleSheet.create({
  headerTextStyle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 18,
    letterSpacing: 0.7,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
    paddingLeft: 15,
    paddingTop: 30,
    paddingRight: 15,
    backgroundColor: 'white',
    overflow: 'hidden',
    position: 'relative',
  },
  headerContainer: {
    display: 'flex',
    flexDirection: 'row',
  },
  bottomGradient: {
    position: 'absolute',
    bottom: 0,
    top: undefined,
    left: 0,
    right: 0,
    width: '120%',
    height: 30,
  },
  cross: {
    alignSelf: 'flex-end',
    marginRight: 10,
    marginTop: 10,
  },
  textWrapper: {
    width: '40%',
    borderStyle: 'solid',
    borderWidth: 0.5,
    borderColor: '#A5A5A5',
    borderRadius: 6,
    height: 45,
    backgroundColor: '#FFFFFF',
    marginTop: 10,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  no: {
    alignSelf: 'center',
    marginTop: screenHeight / 3,
    fontFamily: 'Poppins-Regular',
    fontSize: 18,
    letterSpacing: 0.7,
    color: '#959595',
  },
  itemHeaderTextStyle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.5,
    fontWeight: 'bold',
    width: screenWidth / 1.8,
  },
  itemDescriptionTextStyle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    color: '#8E8E8E',
    fontWeight: '400',
  },
  itemContainer: {
    width: '100%',
    minHeight: 120,
    borderColor: '#EDEDED',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginBottom: 20,
    shadowColor: '#0000000a',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  itemHeaderContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  heartIconContainer: {
    height: 30,
    width: 30,
    borderColor: '#EDEDED',
    borderWidth: 1,
    borderRadius: 5,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemFooterContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  itemFooterButtonsContainer: {
    display: 'flex',
    flexDirection: 'row',
  },
  itemFooterButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 5,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
  },
  bottomDetailsContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  gridContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
    // padding: 10,
    // marginBottom: 20,
  },
  gridButtonContainer: {
    flexBasis: '50%',
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gridIcon: {
    fontSize: 30,
    color: 'white',
  },
  gridLabel: {
    fontSize: 14,
    paddingTop: 10,
    color: '#333',
    marginHorizontal: 8,
  },
  vehtype: {
    alignSelf: 'center',
    color: '#343434',
    fontFamily: 'Poppins-Regular',
    fontSize: 18,
    marginTop: 10,
  },
  // mainWrapper: {
  //   display: 'flex',
  //   alignItems: 'center',
  //   marginTop: 15,
  // },
  vehtypee: {
    alignSelf: 'center',
    color: '#343434',
    fontFamily: 'Poppins-Regular',
    fontSize: 18,
    marginTop: 10,
  },

  header: {
    height: 55,
    padding: 10,
    width: '100%',
    backgroundColor: '#000',
    elevation: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerText: {
    color: '#ff3232',
    fontSize: 22,
    fontWeight: 'bold',
  },
  indicatorContainer: {
    height: height - 170,
    width: width - 30,
    padding: 20,
    paddingTop: 0,
    margin: 15,
    elevation: 10,
    borderRadius: 20,
    backgroundColor: '#000',
  },
  labelContainer: {
    // padding: 10,
    paddingLeft: 5,
    width: width - 100,
  },
  labelText: {
    fontSize: 17,
    color: '#fff',
    fontWeight: 'bold',
  },
  status: {
    fontSize: 15,
    color: 'gray',
  },
  nextBtn: {
    alignSelf: 'flex-end',
  },
  text: {
    color: '#ff3232',
    fontSize: 18,
  },
  vehtype: {
    alignSelf: 'center',
    color: '#343434',
    fontFamily: 'Poppins-Regular',
    fontSize: 18,
    marginTop: 10,
  },
  buttonsText: {
    color: '#FFFFFF',
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
  },
  sub: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    marginVertical: 3,
  },
  subb: {
    width: '50%',
    alignItems: 'flex-start',
  },
  subtop: {
    marginTop: -10,
  },
  vehCont: {
    backgroundColor: '#FFFF',
    maxHeight: 300,
    borderRadius: 10,
  },
  gta: {
    backgroundColor: '#ed4b62',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    height: 40,
    width: screenWidth / 2,
    alignSelf: 'center',
    marginVertical: 20,
  },
  cmod: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
});
export default styles;
